name: crawl2

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  crawl:
    runs-on: ubuntu-latest
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: main_folder
          ref: main

      # Step 2: Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev
          sudo apt-get install -y libfontconfig1-dev build-essential gfortran r-base-dev

      # Step 3: Set up R
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      # Step 4: Set up renv and remove outdated lock file
      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
          working-directory: main_folder

      - name: Remove outdated renv.lock
        working-directory: ./main_folder
        run: |
          if [ -f renv.lock ]; then
            rm renv.lock
          fi

      # Step 5: Pre-install bit package to address compilation issue
      - name: Pre-install bit package
        working-directory: ./main_folder
        run: |
          Rscript -e 'install.packages("bit", repos="https://cloud.r-project.org")'

      # Step 6: Reinitialize renv and install additional packages
      - name: Reinitialize renv and install packages
        working-directory: ./main_folder
        run: |
          options(error = traceback)
          renv::init(bare = TRUE)
          install.packages(c("httr", "jsonlite", "rvest", "dplyr", "purrr"))
          renv::snapshot()

      # Step 7: Create and populate credentials file with secrets
      - name: Create and populate credentials file with secrets
        working-directory: ./main_folder
        run: |
          echo 'openai_apikey="'"$MAPPED_OPENAI_APIKEY"'"' >> credentials.R
          echo 'crossref_email="'"$MAPPED_CROSSREF_EMAIL"'"' >> credentials.R
          echo 'gemini_apikey="'"$MAPPED_GEMINI_APIKEY"'"' >> credentials.R
        shell: bash
        env:
          MAPPED_OPENAI_APIKEY: ${{ secrets.OPENAI_APIKEY }}
          MAPPED_CROSSREF_EMAIL: ${{ secrets.CROSSREF_EMAIL }}
          MAPPED_GEMINI_APIKEY: ${{ secrets.GEMINI_APIKEY }}

      # Step 8: Run R scripts
      - name: Get data and produce JSON
        working-directory: ./main_folder
        run: |
          options(error = traceback)
          Rscript crawl.R "sociology"
          Rscript crawl.R "communication"
          Rscript crawl.R "politics"
          Rscript crawl.R "po"
          Rscript crawl.R "psych"
          Rscript crawl.R "multidisciplinary"
          Rscript preprints.R
          Rscript must_read.R

      # Step 9: Commit results to the main branch
      - name: Commit results to main branch 
        working-directory: ./main_folder
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add . && git commit -m "Data updated"
          git push origin
