name: crawl2

on: 
   workflow_dispatch:
   schedule:
     - cron: "0 2 * * *"

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Cache R packages
        id: cache-r-packages
        uses: actions/cache@v3
        with:
          path: ~/.R/Library
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::httr 
            any::jsonlite
            any::rvest

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: main_folder
          ref: main

      - name: Save R package cache
        if: steps.cache-r-packages.outputs.cache-hit != 'true'
        uses: actions/cache@v3
        with:
          path: ~/.R/Library
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}

      - name: Create and populate credentials file with secrets
        working-directory: ./main_folder
        run: |
          echo 'openai_apikey="'"$MAPPED_OPENAI_APIKEY"'"' >> credentials.R
          echo 'crossref_email="'"$MAPPED_CROSSREF_EMAIL"'"' >> credentials.R
        shell: bash
        env:
          MAPPED_OPENAI_APIKEY : ${{ secrets.OPENAI_APIKEY }}
          MAPPED_CROSSREF_EMAIL : ${{ secrets.CROSSREF_EMAIL }}

      - name: Get data and produce JSON
        working-directory: ./main_folder
        run: |
          Rscript crawl.R "sociology"
          Rscript crawl.R "communication"
          Rscript crawl.R "politics"
          Rscript crawl.R "po"
          Rscript crawl.R "psych"
          Rscript crawl.R "multidisciplinary"

      - name: Commit results main branch 
        working-directory: ./main_folder
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add . && git commit -m "Data updated"
          git push origin